### ISSUE TITLE
Fhler beim aufspielen

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#1]
Hallo,
ich hab die IDE komplett neu installiert nur die Boards und die Libraries aus dem Github
installiert.
TTN Daten sind drin.
Aufspielen bringt:
Der Sketch verwendet 636393 Bytes (9%) des Programmspeicherplatzes. Das Maximum sind 6553600 Bytes.
Globale Variablen verwenden 31876 Bytes (0%) des dynamischen Speichers, 4490108 Bytes für lokale Variablen verbleiben. Das Maximum sind 4521984 Bytes.
esptool.py v2.6
Serial port COM7
Connecting.....
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: f0:08:d1:c7:37:70
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Auto-detected Flash size: 16MB
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 16383.2 kbit/s)...
Hash of data verified.
Flash params set to 0x024f
Compressed 15856 bytes to 10276...
Wrote 15856 bytes (10276 compressed) at 0x00001000 in 0.1 seconds (effective 919.2 kbit/s)...
Hash of data verified.
Compressed 636656 bytes to 221540...
Wrote 636656 bytes (221540 compressed) at 0x00010000 in 5.9 seconds (effective 866.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 129...
Wrote 3072 bytes (129 compressed) at 0x00008000 in 0.0 seconds (effective 4915.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

Monitor bleibt das M5 Stack Logo stehen.

Serrial Log sagt:
12:06:01.276 -> ets Jun  8 2016 00:22:57
12:06:01.276 -> 
12:06:01.276 -> rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
12:06:01.276 -> configsip: 0, SPIWP:0xee
12:06:01.276 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
12:06:01.276 -> mode:DIO, clock div:1
12:06:01.276 -> load:0x3fff0018,len:4
12:06:01.276 -> load:0x3fff001c,len:1044
12:06:01.276 -> load:0x40078000,len:8896
12:06:01.276 -> load:0x40080400,len:5816
12:06:01.276 -> entry 0x400806ac
12:06:03.031 -> M5Stack initializing...OK
12:06:03.706 -> FAILURE 
12:06:03.706 -> C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src\lmic\oslmic.c:53

Danke

**Comment by Bjoerns-TB** [comment]
Hi,

das LoRa Modul wird nicht erkannt. Schau bitte ob es richtig fest mit dem M5 verbunden ist. Gelegentlich haben die Module keine richtige Verbindung untereinander.
Betreibe auch das LoRa Modul mal testweise nur mit dem M5. Zusammen mit der Faces-Tastatur funktioniert es bei mir auch nicht.

**Comment by Lordcybertracker** [comment]
JA hat nicht richtig gesteckt.
