### ISSUE TITLE
No of GWs 0

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#2]
Hallo,
starten tut es jetzt Senden funktioniert auch,
Es kommt bei TTN an. GPS 00000000 da kein Signal im Testbereich
Aber warum bleibt No of GWs 0
Zeigt aber -dB -83 SNR 5.7

**Comment by Bjoerns-TB** [comment]
Hi, 

der Fehler ist bekannt und steht auf meiner Liste.

**Comment by Lordcybertracker** [comment]
OK. Vielen Dank.
Super Arbeit.

**Comment by Bjoerns-TB** [comment]
Hi,

ich hatte etwas vergessen in der Arduino LMIC anzupassen.
Folgendes File müsstes du bitte neu laden:
src/lmic/lmic.c

Dann sollte es gehen.

**Comment by Lordcybertracker** [comment]
ICh hab jetzt alles neu geladen und jetzt etwas neues:
In file included from C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src/arduino_lmic.h:26:0,
                 from C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src/lmic.h:28,
                 from C:\Users\laval\Documents\Arduino\M5Stack-LoRa-868-Network-Tester-main\M5Stack-LoRa-868-Network-Tester-main\networktester\networktester.ino:3:
C:\Users\laval\Documents\Arduino\M5Stack-LoRa-868-Network-Tester-main\M5Stack-LoRa-868-Network-Tester-main\networktester\networktester.ino: In function 'void initlora()':
networktester:504:48: error: 'DR_SF12' was not declared in this scope
   LMIC_setupChannel(0, 868100000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band
                                                ^
C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src/lmic/lmic.h:658:50: note: in definition of macro 'DR_RANGE_MAP'
 #define DR_RANGE_MAP(drlo,drhi) (((u2_t)0xFFFF<<(drlo)) & ((u2_t)0xFFFF>>(15-(drhi))))
                                                  ^
networktester:504:67: error: 'BAND_CENTI' was not declared in this scope
   LMIC_setupChannel(0, 868100000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band
                                                                   ^
In file included from C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src/arduino_lmic.h:26:0,
                 from C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src/lmic.h:28,
                 from C:\Users\laval\Documents\Arduino\M5Stack-LoRa-868-Network-Tester-main\M5Stack-LoRa-868-Network-Tester-main\networktester\networktester.ino:3:
networktester:505:57: error: 'DR_SF7B' was not declared in this scope
   LMIC_setupChannel(1, 868300000, DR_RANGE_MAP(DR_SF12, DR_SF7B), BAND_CENTI);      // g-band
                                                         ^
C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src/lmic/lmic.h:658:79: note: in definition of macro 'DR_RANGE_MAP'
 #define DR_RANGE_MAP(drlo,drhi) (((u2_t)0xFFFF<<(drlo)) & ((u2_t)0xFFFF>>(15-(drhi))))
                                                                               ^
networktester:512:48: error: 'DR_FSK' was not declared in this scope
   LMIC_setupChannel(8, 868800000, DR_RANGE_MAP(DR_FSK,  DR_FSK),  BAND_MILLI);      // g2-band
                                                ^
C:\Users\laval\Documents\Arduino\libraries\arduino-lmic-LMIC_setLinkCheckRequestOnce\src/lmic/lmic.h:658:50: note: in definition of macro 'DR_RANGE_MAP'
 #define DR_RANGE_MAP(drlo,drhi) (((u2_t)0xFFFF<<(drlo)) & ((u2_t)0xFFFF>>(15-(drhi))))
                                                  ^
networktester:512:67: error: 'BAND_MILLI' was not declared in this scope
   LMIC_setupChannel(8, 868800000, DR_RANGE_MAP(DR_FSK,  DR_FSK),  BAND_MILLI);      // g2-band

**Comment by Bjoerns-TB** [comment]
Sag mir kurz was es war, habe auf meinem Testrechner gerade das gleiche Problem.
Danke

**Comment by Lordcybertracker** [comment]
lmic_project_config.h nicht angepasst,
 Hatte ja IDE neu drauf gemacht.

**Comment by Bjoerns-TB** [comment]
Danke
