### ISSUE TITLE
Symbole top und Inactive

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#3]
Hallo
Für was stehen oben die Symbole?
ich hab Denke mal Wlan 0, Grüner Kreis 99,99, Kugel dahinter leer und klar 100% Akku.

Wie bekomme ich das Inactive weg?

**Comment by Bjoerns-TB** [comment]
Hi,

das erste Symbol liefert die sichtbaren Satelliten. Danach kommt der HDOP Wert. Bei 99.99 wird dein GPS Modul erkannt, bei 0 nicht. Die Kugel danach wird grün sobald win GPS Fix vorhanden ist. Steckt eine SD Karte wird auch dafür ein Symbol angezeigt. Abschließend kommt der Akkustand.

Das Inactive verschwindet sobald du ein GPS Signal hast, ansonsten wird nichts verschickt.

**Comment by Lordcybertracker** [comment]
Danke.
