### ISSUE TITLE
ACK geht geht nich t zurück

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#5]
Hallo,
im ACK Modus bleibt er beim letzten wert Stehen.
Es wäre besser wenn er danach nichts empfängt auf dB -130 wieder geht.

**Comment by Bjoerns-TB** [comment]
Hi, ist angepasst.
Die Werte werden nun zurückgesetzt, sollte kein ACK empfangen werden.

**Comment by Lordcybertracker** [comment]
Danke.Wird morgen gleich alles getestet. Super Arbeit. 
-------- Ursprüngliche Nachricht --------Von: Björn Amann <notifications@github.com> Datum: 04.01.21  22:45  (GMT+01:00) An: Bjoerns-TB/M5Stack-LoRa-868-Network-Tester <M5Stack-LoRa-868-Network-Tester@noreply.github.com> Cc: Lordcybertracker <lord_cybertracker@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester] ACK geht geht nich t zurück (#5) 

Hi, ist angepasst.

Die Werte werden nun zurückgesetzt, sollte kein ACK empfangen werden.
