### ISSUE TITLE
Ton ausgabe

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#6]
Hallo,
wäre es das er wenn er eien Rückmeldung bekommt einen Ton aus dem Internen Lautsprecher ausgibt?
Wenn das Gerät im Auto verwendet wird wäre das von Vorteil. Da man nicht immer hinsehen muß.

**Comment by Bjoerns-TB** [comment]
Ich finde die Idee gut und habe jetzt mal einen Beep eingebaut.
