### ISSUE TITLE
Singel GW werden nicht erkannt

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#7]
Ich hab 2 Singel GWs aufgebaut. 
Beide auf SF7 diese werden komplett ignoriert.

**Comment by Bjoerns-TB** [comment]
Was bedeutet ignoriert?

Generell sind Single Channels GWs nur zum Testen brauchbar. Sie sind auf einen SF und eine Frequenz fest eingestellt. Somit empfangen sie generell nur 1/8 aller Pakete eines Nodes. Hinzu kommt der oft fehlende Uplink support.

**Comment by Lordcybertracker** [comment]
Ok danke.
Dual funktionieren das kann ich schon mal Bestätigen
Getestet mit Heltec HL-M00.
