### ISSUE TITLE
RGB LED Seiten Wechseln

### ISSUE THREAD

**Issue by Lordcybertracker** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#8]
Da die GPS LED ja eher weniger Interessant ist.
Aber die Stärke LEDs bei den Steckern sind wollte ich fragen ob man die Seiten einfach tauschen kann?
Auch für die welche vielleicht mein Gehäuse nachbauen. Da scheinen die Rechten LEDs durch.

Mal sehen bis wann ich dich Nerve. :P

**Comment by Bjoerns-TB** [comment]
Ich werde das nicht anpassen, aber du kannst es gerne für dich selber ändern:

strip.SetPixelColor(0, colour); -> strip.SetPixelColor(5, colour);
strip.SetPixelColor(2, colour); -> strip.SetPixelColor(7, colour);
strip.SetPixelColor(4, colour); -> strip.SetPixelColor(9, colour);
strip.SetPixelColor(7, colour); -> strip.SetPixelColor(2, colour);

Damit hättest du alles umgedreht.

**Comment by Lordcybertracker** [comment]
Vielen Dank.
