### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by JamesT42** [Bjoerns-TB/M5Stack-LoRa-868-Network-Tester#9]
Hi!
Can you please help me with this, I googled for hours but I do not know what is going on.

The process just end with 
exit status 1
Error compiling for board M5Stack-FIRE.
This is the full output: [errors.txt](https://github.com/Bjoerns-TB/M5Stack-LoRa-868-Network-Tester/files/6177232/errors.txt)

Thanks
James

**Comment by Bjoerns-TB** [comment]
Hi James,

it looks like a problem with M5_UI
`E:\-=VID=-\Arduino\libraries\M5_UI-TTN-Mapper-Colours-Progressbar\M5_UI.cpp: In function 'void UIDrawSelectbox(int)':

E:\-=VID=-\Arduino\libraries\M5_UI-TTN-Mapper-Colours-Progressbar\M5_UI.cpp:765:9: warning: unused variable 'selectedId' [-Wunused-variable]

     int selectedId = 0;

         ^

E:\-=VID=-\Arduino\libraries\M5_UI-TTN-Mapper-Colours-Progressbar\M5_UI.cpp: In function 'String UIOptionValue(String*)':

E:\-=VID=-\Arduino\libraries\M5_UI-TTN-Mapper-Colours-Progressbar\M5_UI.cpp:420:1: error: control reaches end of non-void function [-Werror=return-type]

 }`

I tried to compile it from scratch and have no issues. Try to remove M5_UI from your library folder and download it again from GitHub as ZIP. Than add it through arduino (Add .ZIP library). 

Hope it helps,
Björn

**Comment by JamesT42** [comment]
Hi!
I tried that, does not change anything :(
I googled for some more hours and it seems that you need a return statement at the end of the String UIOptionValue(String* rootVar) function in M5_UI.cpp (see following code)

```
String UIOptionValue(String* rootVar) {
	int optionsCount = cntChar(*rootVar, (char)0x1E);
    for (int i = 0; i < optionsCount; i++)
    {
      String selected = parseString(2, (char)0x1F, parseString(i, (char)0x1E, *rootVar));
      if (selected == "true")
      {
        return parseString(1, (char)0x1F, parseString(i, (char)0x1E, *rootVar));
      }
    }
	return strdup("");
}
```

Do you have the latest version of the Arduino IDE and/or the ESP32 Board files? I read somewhere that this might be a result of a recent change in the compiler, before it was just a warning, now it generates an error.

**Comment by Bjoerns-TB** [comment]
Hi,

i tested it again on Win10 and Ubuntu and it compiles fine. I completely reinstalled the IDE with the latest versions. The only messages i get are the 
`warning: ISO C++ forbids converting a string constant to 'char*'` warnings.

**Comment by JamesT42** [comment]
Can you post the full buildlog from your Windows test?

**Comment by Bjoerns-TB** [comment]
Ok, now i can confirm the error.
I removed the temporary files, so all had to be recompiled and now i am getting the same error.
I will try to fix it.

**Comment by JamesT42** [comment]
My fix works so far, but may not be correct...

**Comment by Bjoerns-TB** [comment]
I think i fixed it ;-)
I removed (commented)  the variable 'selectedId' and the function 'String UIOptionValue(String*). It is unused and not needed. So this should not hurt.

**Comment by Bjoerns-TB** [comment]
Another option seems to compile it with compiler warnings deactivated under preferences.
